package functions

import (
	"fmt"
	"strings"
)

//Setcodes map of all current MTG sets
var Setcodes = map[string]string{
	"Core 2019":                      "M19",
	"Dominaria":                      "DOM",
	"Masters 25":                     "A25",
	"Rivals of Ixalan":               "RIX",
	"Unstable":                       "UST",
	"From the Vault: Transform":      "V17",
	"Explorers of Ixalan":            "E02",
	"Iconic Masters":                 "IMA",
	"Duel Decks: Merfolk vs Goblins": "DDT",
	"Ixalan":                 "XLN",
	"Commander 2017":         "C17",
	"Hour of Devastation":    "HOU",
	"Archenemy: Nicol Bolas": "AC2",
	"Commander Anthology":    "CMT",
	"Amonkhet":               "AKH",
	"Masterpiece Series: Amonkhet Invocations": "AKHMPS",
	"Duel Decks: Mind vs Might":                "DDS",
	"Modern Masters 2017 Edition":              "MM3",
	"Aether Revolt":                            "AER",
	"Planechase Anthology":                     "PCA",
	"Commander 2016":                           "C16",
	"Kaladesh":                                 "KLD",
	"Masterpiece Series: Kaladesh Inventions": "MPS",
	"Duel Decks: Nissa vs. Ob Nixilis":        "DDR",
	"Conspiracy: Take the Crown":              "CN2",
	"From the Vault: Lore":                    "V16",
	"Eldritch Moon":                           "EMN",
	"Eternal Masters":                         "EMA",
	"Shadows over Innistrad":                  "SOI",
	"Welcome Deck 2016":                       "W16",
	"Duel Decks: Blessed vs Cursed":           "DDQ",
	"Oath of the Gatewatch":                   "OGW",
	"Commander 2015":                          "C15",
	"Battle for Zendikar":                     "BFZ",
	"Zendikar Expeditions":                    "EXP",
	"Duel Decks: Zendikar vs Eldrazi":         "DDP",
	"From the Vault: Angels":                  "V15",
	"Magic Origins":                           "ORI",
	"Modern Masters 2015 Edition":             "MM2",
	"Tempest Remastered":                      "TPR",
	"Dragons of Tarkir":                       "DTK",
	"Duel Decks: Elspeth vs Kiora":            "DDO",
	"Fate Reforged":                           "FRF",
	"Commander 2014":                          "C14",
	"Khans of Tarkir":                         "KTK",
	"Duel Decks: Speed vs Cunning":            "DDN",
	"From the Vault: Annihilation":            "V14",
	"Magic 2015":                              "M15",
	"Vintage Masters":                         "VMA",
	"Conspiracy":                              "CNS",
	"Modern Event Deck":                       "MD1",
	"Journey into Nyx":                        "JOU",
	"Duel Decks: Jace vs Vraska":              "DDM",
	"Born of the Gods":                        "BNG",
	"Commander 2013":                          "C13",
	"Theros":                                  "THS",
	"Duel Decks: Heroes vs. Monsters":         "DDL",
	"From the Vault: Twenty":                  "V13",
	"Magic 2014":                              "M14",
	"Modern Masters":                          "MMA",
	"Duel Decks: Sorin vs. Tibalt":            "DDK",
	"Dragon's Maze":                           "DGM",
	"Gatecrash":                               "GTC",
	"Coldsnap Theme Deck":                     "CTD",
	"Commander's Arsenal":                     "CMA",
	"Return to Ravnica":                       "RTR",
	"Duel Decks: Izzet vs. Golgari":           "DDJ",
	"From the Vault: Realms":                  "V12",
	"Magic 2013":                              "M13",
	"Planechase 2012 Edition":                 "PC2",
	"Avacyn Restored":                         "AVR",
	"Duel Decks: Venser vs. Koth":             "DDI",
	"Dark Ascension":                          "DKA",
	"Premium Deck Series: Graveborn":          "GRV",
	"Innistrad":                               "ISD",
	"Duel Decks: Ajani vs. Nicol Bolas":       "DDH",
	"From the Vault: Legends":                 "V11",
	"2012 Core Set":                           "M12",
	"MTG: Commander":                          "CMD",
	"New Phyrexia":                            "NPH",
	"Duel Decks: Knights vs. Dragons":         "DDG",
	"Mirrodin Besieged":                       "MBS",
	"Mirrodin Besieged: Mirran":               "MBM",
	"Mirrodin Besieged: Phyrexia":             "MBP",
	"Masters Edition IV":                      "ME4",
	"Premium Deck Series: Fire and Lightning": "PD2",
	"Scars of Mirrodin":                       "SOM",
	"Duel Decks: Elspeth vs. Tezzeret":        "DDF",
	"From the Vault: Relics":                  "V10",
	"2011 Core Set":                           "M11",
	"Archenemy":                               "ARC",
	"Duel Decks: Garruk vs. Liliana":          "DDD",
	"Duels of the Planeswalkers":              "DPA",
	"Duel Decks: Phyrexia vs. The Coalition":  "DDE",
	"Rise of the Eldrazi":                     "ROE",
	"Worldwake":                               "WWK",
	"Premium Deck Series: Slivers":            "PDS",
	"Zendikar":                                "ZEN",
	"Masters Edition III":                     "ME3",
	"Planechase":                              "HOP",
	"From the Vault: Exiled":                  "V09",
	"2010 Core Set":                           "M10",
	"Alara Reborn":                            "ARB",
	"Duel Decks: Divine vs. Demonic":          "DDC",
	"Conflux":                                 "CON",
	"Duel Decks: Jace vs. Chandra":            "DD2",
	"Shards of Alara":                         "ALA",
	"Masters Edition II":                      "ME2",
	"From the Vault: Dragons":                 "DRB",
	"Eventide":                                "EVE",
	"Shadowmoor":                              "SHM",
	"Morningtide":                             "MOR",
	"Duel Decks: Elves vs. Goblins":           "EVG",
	"Lorwyn":                                  "LRW",
	"Masters Edition":                         "MED",
	"Tenth Edition":                           "10E",
	"Future Sight":                            "FUT",
	"Planar Chaos":                            "PLC",
	"FNM Promos":                              "FNM",
	"Time Spiral":                             "TSP",
	"Timeshifted":                             "TSB",
	"Coldsnap":                                "CSP",
	"Dissension":                              "DIS",
	"Guildpact":                               "GPT",
	"Ravnica: City of Guilds":                 "RAV",
	"Ninth Edition":                           "9ED",
	"Saviors of Kamigawa":                     "SOK",
	"Betrayers of Kamigawa":                   "BOK",
	"Unhinged":                                "UNH",
	"Champions of Kamigawa":                   "CHK",
	"Fifth Dawn":                              "5DN",
	"Darksteel":                               "DST",
	"Mirrodin":                                "MRD",
	"Eighth Edition":                          "8ED",
	"Scourge":                                 "SCG",
	"Legions":                                 "LGN",
	"Onslaught":                               "ONS",
	"Judgment":                                "JUD",
	"Torment":                                 "TOR",
	"Deckmasters: Garfield vs. Finkel":        "DKM",
	"Odyssey":                                 "ODY",
	"Guru Lands":                              "GUR",
	"Apocalypse":                              "APC",
	"Seventh Edition":                         "7ED",
	"Planeshift":                              "PLS",
	"Vanguard":                                "VNG",
	"Beatdown Box Set":                        "BTD",
	"Invasion":                                "INV",
	"Prophecy":                                "PCY",
	"Starter 2000":                            "S00",
	"Nemesis":                                 "NMS",
	"Battle Royale Box Set":                   "BRB",
	"Mercadian Masques":                       "MMQ",
	"Starter 1999":                            "S99",
	"Portal Three Kingdoms":                   "PTK",
	"Urza's Destiny":                          "UDS",
	"Classic Sixth Edition":                   "6ED",
	"Urza's Legacy":                           "ULG",
	"Anthologies":                             "ATH",
	"Urza's Saga":                             "USG",
	"Unglued":                                 "UGL",
	"Portal Second Age":                       "P02",
	"Exodus":                                  "EXO",
	"Stronghold":                              "STH",
	"Tempest":                                 "TMP",
	"Weatherlight":                            "WTH",
	"Portal":                                  "POR",
	"Fifth Edition":                           "5ED",
	"Visions":                                 "VIS",
	"Mirage":                                  "MIR",
	"Alliances":                               "ALL",
	"Homelands":                               "HML",
	"Ice Age":                                 "ICE",
	"Chronicles":                              "CHR",
	"Fourth Edition":                          "4ED",
	"Fallen Empires":                          "FEM",
	"The Dark":                                "DRK",
	"Legends":                                 "LEG",
	"Revised Edition":                         "3ED",
	"Antiquities":                             "ATQ",
	"Arabian Nights":                          "ARN",
	"Unlimited Edition":                       "2ED",
	"Collector's Edition":                     "CED",
	"International Collector's Edition":       "CEI",
	"Limited Edition Beta":                    "LEB",
	"Limited Edition Alpha":                   "LEA",
	"Promo set for Gatherer":                  "PSG",
	"Magic Online Promo Cards":                "MOP"}
var setmatch string

//SetName iterates through and matches ID and name
func SetName(setcode string) string {
	var splitString = strings.Split(setcode, " ")
	setmatch = "Could not find match"
	if len(splitString) != 2 {
		return "Please Submit Setcode in format : !set *XYZ*"
	}
	setcode = strings.ToUpper(splitString[1])
	fmt.Println(setcode)
	for names, v := range Setcodes {
		if v == setcode {
			setmatch = names
			break
		}
	}
	return setmatch
}
